
services:
  db:
    image: postgres:15
    container_name: sitesync_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sitesync
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sitesync
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: sitesync_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: .
    image: sitesync_api:dev
    container_name: sitesync_api
    depends_on:
      - db
      - minio
    environment:
      - ENV_FILE=.env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  db_data:
  minio_data:
