"""Add comprehensive site profile fields

Revision ID: 4e666e97cb0e
Revises: bfe077b4b23f
Create Date: 2025-09-27 15:51:54.460693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e666e97cb0e'
down_revision: Union[str, None] = 'bfe077b4b23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('pi_name', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('institution', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('sites', sa.Column('age_ranges_served', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('health_status_experience', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('annual_patient_volume', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('recruitment_sources', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('competing_studies_count', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('complex_assessments_capable', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('washout_capability', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('pk_sampling_capable', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('special_equipment', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('available_procedures', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('total_research_staff', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('coordinators_fte', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('available_for_training', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('weekend_coverage', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('specialist_access', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('avg_recruitment_hours_per_study', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('avg_visit_hours_per_study', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('monitor_visit_capacity', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('edc_experience', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('convenient_scheduling', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('previous_sponsors', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('phase_experience', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('therapeutic_areas', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('profile_completion_percentage', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('profile_last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'profile_last_updated')
    op.drop_column('sites', 'profile_completion_percentage')
    op.drop_column('sites', 'therapeutic_areas')
    op.drop_column('sites', 'phase_experience')
    op.drop_column('sites', 'previous_sponsors')
    op.drop_column('sites', 'convenient_scheduling')
    op.drop_column('sites', 'edc_experience')
    op.drop_column('sites', 'monitor_visit_capacity')
    op.drop_column('sites', 'avg_visit_hours_per_study')
    op.drop_column('sites', 'avg_recruitment_hours_per_study')
    op.drop_column('sites', 'specialist_access')
    op.drop_column('sites', 'weekend_coverage')
    op.drop_column('sites', 'available_for_training')
    op.drop_column('sites', 'coordinators_fte')
    op.drop_column('sites', 'total_research_staff')
    op.drop_column('sites', 'available_procedures')
    op.drop_column('sites', 'special_equipment')
    op.drop_column('sites', 'pk_sampling_capable')
    op.drop_column('sites', 'washout_capability')
    op.drop_column('sites', 'complex_assessments_capable')
    op.drop_column('sites', 'competing_studies_count')
    op.drop_column('sites', 'recruitment_sources')
    op.drop_column('sites', 'annual_patient_volume')
    op.drop_column('sites', 'health_status_experience')
    op.drop_column('sites', 'age_ranges_served')
    op.drop_column('sites', 'contact_phone')
    op.drop_column('sites', 'contact_email')
    op.drop_column('sites', 'institution')
    op.drop_column('sites', 'pi_name')
    # ### end Alembic commands ###
